"""
HomeIQ — Strongly-Typed Enumerations for the Normalized Household Schema.
"""
try:
    from enum import StrEnum
except ImportError:
    from enum import Enum

    class StrEnum(str, Enum):  # type: ignore[no-redef]
        pass


class HouseholdRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    ADULT_MEMBER = "ADULT_MEMBER"
    JUNIOR_MEMBER = "JUNIOR_MEMBER"
    GUEST = "GUEST"


class AssetCategory(StrEnum):
    APPLIANCE = "APPLIANCE"
    VEHICLE = "VEHICLE"
    ELECTRONICS = "ELECTRONICS"
    HVAC_PLUMBING = "HVAC_PLUMBING"
    FURNITURE_FIXTURE = "FURNITURE_FIXTURE"
    STRUCTURAL = "STRUCTURAL"
    OTHER = "OTHER"


class AssetStatus(StrEnum):
    ACTIVE = "ACTIVE"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    STORED = "STORED"
    RETIRED = "RETIRED"
    DISPOSED = "DISPOSED"


class ApplianceType(StrEnum):
    REFRIGERATOR = "REFRIGERATOR"
    DISHWASHER = "DISHWASHER"
    WASHING_MACHINE = "WASHING_MACHINE"
    DRYER = "DRYER"
    AIR_CONDITIONER = "AIR_CONDITIONER"
    WATER_PURIFIER = "WATER_PURIFIER"
    MICROWAVE_OVEN = "MICROWAVE_OVEN"
    WATER_HEATER = "WATER_HEATER"
    VACUUM_ROBOT = "VACUUM_ROBOT"
    OTHER = "OTHER"


class VehicleType(StrEnum):
    CAR = "CAR"
    TWO_WHEELER = "TWO_WHEELER"
    BICYCLE = "BICYCLE"
    COMMERCIAL = "COMMERCIAL"
    OTHER = "OTHER"


class FuelType(StrEnum):
    PETROL = "PETROL"
    DIESEL = "DIESEL"
    ELECTRIC = "ELECTRIC"
    HYBRID = "HYBRID"
    CNG = "CNG"
    NONE = "NONE"


class MeasurementUnit(StrEnum):
    GRAM = "GRAM"
    KILOGRAM = "KILOGRAM"
    MILLILITER = "MILLILITER"
    LITER = "LITER"
    PIECE = "PIECE"
    PACK = "PACK"
    DOZEN = "DOZEN"


class GroceryCategory(StrEnum):
    PRODUCE = "PRODUCE"
    DAIRY_EGGS = "DAIRY_EGGS"
    GRAINS_PULSES = "GRAINS_PULSES"
    SPICES_CONDIMENTS = "SPICES_CONDIMENTS"
    BEVERAGES = "BEVERAGES"
    FROZEN = "FROZEN"
    HOUSEHOLD_SUPPLIES = "HOUSEHOLD_SUPPLIES"
    OTHER = "OTHER"


class StockStatus(StrEnum):
    IN_STOCK = "IN_STOCK"
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    EXPIRED = "EXPIRED"


class StorageLocation(StrEnum):
    PANTRY = "PANTRY"
    REFRIGERATOR = "REFRIGERATOR"
    FREEZER = "FREEZER"
    UTILITY_CLOSET = "UTILITY_CLOSET"
    GARAGE = "GARAGE"
    MEDICINE_CABINET = "MEDICINE_CABINET"
    OTHER = "OTHER"


class GarmentCategory(StrEnum):
    FORMAL_WEAR = "FORMAL_WEAR"
    CASUAL_WEAR = "CASUAL_WEAR"
    ACTIVE_WEAR = "ACTIVE_WEAR"
    ETHNIC_TRADITIONAL = "ETHNIC_TRADITIONAL"
    OUTERWEAR = "OUTERWEAR"
    LINEN_BEDDING = "LINEN_BEDDING"
    DELICATES = "DELICATES"


class WashCareMethod(StrEnum):
    MACHINE_WASH_COLD = "MACHINE_WASH_COLD"
    MACHINE_WASH_WARM = "MACHINE_WASH_WARM"
    DELICATE_GENTLE = "DELICATE_GENTLE"
    HAND_WASH_ONLY = "HAND_WASH_ONLY"
    DRY_CLEAN_ONLY = "DRY_CLEAN_ONLY"


class LaundryStatus(StrEnum):
    CLEAN_IN_WARDROBE = "CLEAN_IN_WARDROBE"
    IN_LAUNDRY_BASKET = "IN_LAUNDRY_BASKET"
    AT_DRY_CLEANER = "AT_DRY_CLEANER"
    NEEDS_REPAIR = "NEEDS_REPAIR"


class BillCategory(StrEnum):
    ELECTRICITY = "ELECTRICITY"
    WATER_SEWAGE = "WATER_SEWAGE"
    PIPED_GAS = "PIPED_GAS"
    BROADBAND_INTERNET = "BROADBAND_INTERNET"
    MOBILE_POSTPAID = "MOBILE_POSTPAID"
    SOCIETY_MAINTENANCE = "SOCIETY_MAINTENANCE"
    PROPERTY_TAX = "PROPERTY_TAX"
    OTHER = "OTHER"


class BillStatus(StrEnum):
    UPCOMING = "UPCOMING"
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    DISPUTED = "DISPUTED"


class ExpenseCategory(StrEnum):
    GROCERIES = "GROCERIES"
    UTILITIES = "UTILITIES"
    HOME_MAINTENANCE = "HOME_MAINTENANCE"
    VEHICLE_FUEL_SERVICE = "VEHICLE_FUEL_SERVICE"
    LAUNDRY_CARE = "LAUNDRY_CARE"
    INSURANCE_PREMIUM = "INSURANCE_PREMIUM"
    SUBSCRIPTIONS = "SUBSCRIPTIONS"
    ASSET_PURCHASE = "ASSET_PURCHASE"
    HEALTH_HOUSEHOLD = "HEALTH_HOUSEHOLD"
    OTHER = "OTHER"


class PaymentMethod(StrEnum):
    UPI = "UPI"
    CREDIT_CARD = "CREDIT_CARD"
    DEBIT_CARD = "DEBIT_CARD"
    NET_BANKING = "NET_BANKING"
    AUTO_DEBIT_NACH = "AUTO_DEBIT_NACH"
    CASH = "CASH"


class BillingCycle(StrEnum):
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    SEMI_ANNUAL = "SEMI_ANNUAL"
    ANNUAL = "ANNUAL"


class SubscriptionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"
    TRIAL = "TRIAL"


class MaintenanceType(StrEnum):
    PREVENTIVE_SERVICE = "PREVENTIVE_SERVICE"
    BREAKDOWN_REPAIR = "BREAKDOWN_REPAIR"
    FILTER_PART_REPLACEMENT = "FILTER_PART_REPLACEMENT"
    INSPECTION_CERTIFICATION = "INSPECTION_CERTIFICATION"
    INSTALLATION = "INSTALLATION"


class MaintenanceStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class DocumentType(StrEnum):
    INVOICE_RECEIPT = "INVOICE_RECEIPT"
    WARRANTY_CERTIFICATE = "WARRANTY_CERTIFICATE"
    INSURANCE_POLICY = "INSURANCE_POLICY"
    APPLIANCE_MANUAL = "APPLIANCE_MANUAL"
    UTILITY_BILL = "UTILITY_BILL"
    VEHICLE_REGISTRATION_PUC = "VEHICLE_REGISTRATION_PUC"
    PROPERTY_LEGAL = "PROPERTY_LEGAL"
    IDENTITY_COMPLIANCE = "IDENTITY_COMPLIANCE"
    OTHER = "OTHER"


class WarrantyType(StrEnum):
    MANUFACTURER_STANDARD = "MANUFACTURER_STANDARD"
    EXTENDED_WARRANTY = "EXTENDED_WARRANTY"
    AMC_CONTRACT = "AMC_CONTRACT"
    COMPONENT_SPECIFIC = "COMPONENT_SPECIFIC"


class WarrantyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRING_SOON = "EXPIRING_SOON"
    EXPIRED = "EXPIRED"
    CLAIMED = "CLAIMED"


class InsuranceType(StrEnum):
    MOTOR_COMPREHENSIVE = "MOTOR_COMPREHENSIVE"
    MOTOR_THIRD_PARTY = "MOTOR_THIRD_PARTY"
    HOME_STRUCTURE_CONTENT = "HOME_STRUCTURE_CONTENT"
    APPLIANCE_PROTECTION = "APPLIANCE_PROTECTION"
    HEALTH_FAMILY_FLOATER = "HEALTH_FAMILY_FLOATER"
    TERM_LIFE = "TERM_LIFE"


class ReminderPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReminderStatus(StrEnum):
    PENDING = "PENDING"
    SNOOZED = "SNOOZED"
    COMPLETED = "COMPLETED"
    DISMISSED = "DISMISSED"


class EventSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AgentRunStatus(StrEnum):
    RUNNING = "RUNNING"
    AWAITING_HUMAN_APPROVAL = "AWAITING_HUMAN_APPROVAL"
    APPROVED_COMPLETED = "APPROVED_COMPLETED"
    COMPLETED = "COMPLETED"
    REJECTED_BY_USER = "REJECTED_BY_USER"
    FAILED = "FAILED"


class ActionRiskLevel(StrEnum):
    READ_ONLY = "READ_ONLY"
    INTERNAL_MUTATION = "INTERNAL_MUTATION"
    EXTERNAL_CONSEQUENTIAL = "EXTERNAL_CONSEQUENTIAL"


class NotificationChannel(StrEnum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    PUSH = "PUSH"
    SMS_WHATSAPP = "SMS_WHATSAPP"


class NotificationStatus(StrEnum):
    UNREAD = "UNREAD"
    READ = "READ"
    ARCHIVED = "ARCHIVED"
